# Spring Boot configuration
spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: borelmba@gmail.com
    password: kxyi rybx olvk hxkw

    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000